# Site settings
title: Research Resources Hub # 网站标题
email: your-email@example.com # 你的联系邮箱
description: >- # 网站描述，更专业化
  A curated collection of free vector graphics tailored for academic and professional use.
  Enhance your presentations, publications, and research visualizations with high-quality, ready-to-use assets.
baseurl: "/Material_base" # <-- 重要：请根据你的GitHub仓库名调整。如果是 iamklufee.github.io，这里应是 ""
url: "https://iamklufee.github.io" # <-- 重要：你的GitHub Pages域名部分

# Collections for materials
collections:
  vectors:
    output: true
    permalink: /vectors/:title/

# Build settings
markdown: kramdown
theme: minima # 可以保留默认主题，但我们将通过自定义CSS覆盖其样式
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap # 推荐添加，用于生成站点地图

# Exclude files/folders from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache
  # 添加任何你不想部署到网站上的文件或文件夹